feat(server): bub-mdt compatibility
Maximus7474/lb-tablet-dispatch-converter pull request #7
Opened 2024-12-30 09:16 UTC by its4lion

### Pull Request Description

Added support for **bub-mdt dispatch**. (Not tested in-game)

## Major Changes
- Added compatibility for [bub-mdt](https://github.com/BubbleDK/bub-mdt).

## Modifications done:
- [x] 🍃 New Feature  
- [ ] ♻️ Refactor  
- [ ] 🐛 Bug Fix  
- [ ] 🎨 Design  
- [ ] 🔥 Optimization  
- [ ] 🎒 Other

2024-12-30 09:54 UTC, Maximus7474 commented
Hi Lion,

Thanks for your contribution, however when lookign through the source code for bub mdt I noticed that the event you've integrated doesn't seem to be the recommended method to create calls, it rather gets scripts to create calls using a server export.
I'll add a quick structure and test it to your branch that will provide support to handling exports for that ressource.

2024-12-30 09:58 UTC, Maximus7474 commented on server/bub-mdt.lua
> +        fields = data?.info or {}
This field can cause issues such as tablet crashes on the current version (1.0.1) as the tablet only supports [IonIcons V5](https://react-icons.github.io/react-icons/icons/io5/), soon it will support [font awesome](https://fontawesome.com/search?m=free&o=r) as well and shouldn't crash.
Do you know what icon references bub-mdt uses ?

2024-12-30 09:59 UTC, Maximus7474 commented on server/bub-mdt.lua
> +            label = data?.location or data?.offense or T("DEFAULT.LOCATION_LABEL"),
`data.location` seems to always be empty ?
> [`server/calls.lua:L18`](https://github.com/BubbleDK/bub-mdt/blob/main/server/calls.lua#L18)

2024-12-30 10:00 UTC, Maximus7474 requested changes
Needs clarifications on certain implementations.

2024-12-30 10:09 UTC, its4lion commented on server/bub-mdt.lua
> +        fields = data?.info or {}
they use @tabler/icons-react

2024-12-30 10:12 UTC, its4lion commented on server/bub-mdt.lua
> +            label = data?.location or data?.offense or T("DEFAULT.LOCATION_LABEL"),
Yes, you're right that `data?.location` is empty, but I keep it so it updates and uses the location when available. It's already linked with the UI.

2024-12-30 10:54 UTC, Maximus7474 commented on server/bub-mdt.lua
> +            label = data?.location or data?.offense or T("DEFAULT.LOCATION_LABEL"),
Yeah that's going to cause an issue if location is `""` the lua SCRT will consider it as valid and always set the label as an empty string, here's a quick example that I ran in fxserver:
```lua
print('^4Lua Testing^7')

local data = {
    location = "",
    offence = "manslaughter"
}

print(('Title: ^3%s^7'):format(data?.location or data?.offence or "DEFAULT"))
``` 
Output:
```bash
11:52:15 [script:lb-tablet-dis] Lua Testing
11:52:15 [script:lb-tablet-dis] Title: 
```
![image](https://github.com/user-attachments/assets/c7d9c346-0cbe-4739-8808-ae0466314b57)

2024-12-30 22:00 UTC, Maximus7474 commented
I'll let you resolve the last comment and update the README and it should be good to merge.

2024-12-31 03:32 UTC, its4lion commented on server/bub-mdt.lua
> +            label = data?.location or data?.offense or T("DEFAULT.LOCATION_LABEL"),
I think this works well:
```suggestion
            label = ((data?.location ~= nil and data?.location ~= "") and data?.location or data?.offense or T("DEFAULT.LOCATION_LABEL"))
```

2024-12-31 04:07 UTC, its4lion commented
I’ve made the necessary changes and updated the README as requested. 
Apologies for any mistakes. I'm still learning how pull requests work. Thanks for your patience!

2024-12-31 10:31 UTC, Maximus7474 approved these changes

2024-12-31 10:32 UTC, Maximus7474 commented
All good, everyone has to learn one way or another !

2024-12-31 10:32 UTC, merged